#!/bin/bash
#scrapes chat from turntable.fm and displays in a terminal
username=$1
regex='~m~[0-9]\{1,9\}\~m\~{\"command\":\ \"speak\"\,\ \"userid\": \"\([0-9]\|[a-z]\)\{1,24\}\"\, \"name\": \"'

sudo tcpdump -i eth0 'port 80' -A | grep --line-buffered "$regex" | \
	awk -v _username=$username \
	    -v N=16 -F\" \
			'{if ($12~_username) 
				printf "\033[1;34m" $12 "\033[0m" ": "; 
			  else 
				printf "\033[1;33m" $12 "\033[0m" ": "; 
			  for (i=N; i<NF; i++) 
				printf $i; 
				print " "
			 }'
